// react-vant/rsbuild/src/App.tsx
import { Flex, CellGroup, Cell } from 'react-vant';
import {
  Records,
  Tosend,
  Logistics,
  PendingPayment,
  Points,
  GoldCoinO,
  GiftO,
} from '@react-vant/icons';
import './App.scss';

const App = () => (
  <div className="container-box">
    <main>
      <div>
        <img
          className="user-poster"
          src="https://img.yzcdn.cn/public_files/2017/10/23/8690bb321356070e0b8c4404d087f8fd.png"
        />
        <Flex className="user-links">
          <Flex.Item span="6">
            <PendingPayment />
            待付款
          </Flex.Item>
          <Flex.Item span="6">
            <Records />
            待接单
          </Flex.Item>
          <Flex.Item span="6">
            <Tosend />
            待发货
          </Flex.Item>
          <Flex.Item span="6">
            <Logistics />
            已发货
          </Flex.Item>
        </Flex>

        <CellGroup className="user-group">
          <Cell icon={<Records />} title="全部订单" isLink />
        </CellGroup>

        <CellGroup>
          <Cell icon={<Points />} title="我的积分" isLink />
          <Cell icon={<GoldCoinO />} title="我的优惠券" isLink />
          <Cell icon={<GiftO />} title="我收到的礼物" isLink />
        </CellGroup>
      </div>
    </main>
  </div>
);

export default App;

// vant/vite/src/App.vue
<template>
  <div>
    <img
      class="user-poster"
      src="https://img.yzcdn.cn/public_files/2017/10/23/8690bb321356070e0b8c4404d087f8fd.png"
    />
    <van-row class="user-links">
      <van-col span="6">
        <van-icon name="pending-payment" />
        待付款
      </van-col>
      <van-col span="6">
        <van-icon name="records" />
        待接单
      </van-col>
      <van-col span="6">
        <van-icon name="tosend" />
        待发货
      </van-col>
      <van-col span="6">
        <van-icon name="logistics" />
        已发货
      </van-col>
    </van-row>

    <van-cell-group class="user-group">
      <van-cell icon="records" title="全部订单" is-link />
    </van-cell-group>

    <van-cell-group>
      <van-cell icon="points" title="我的积分" is-link />
      <van-cell icon="gold-coin-o" title="我的优惠券" is-link />
      <van-cell icon="gift-o" title="我收到的礼物" is-link />
    </van-cell-group>
  </div>
</template>

<script>
import { Row, Col, Icon, Cell, CellGroup } from 'vant';

export default {
  components: {
    [Row.name]: Row,
    [Col.name]: Col,
    [Icon.name]: Icon,
    [Cell.name]: Cell,
    [CellGroup.name]: CellGroup,
  },
};
</script>

<style lang="less">
body {
  font-size: 16px;
  background-color: #f8f8f8;
  -webkit-font-smoothing: antialiased;
}

.user {
  &-poster {
    width: 100%;
    height: 53vw;
    display: block;
  }

  &-group {
    margin-bottom: 15px;
  }

  &-links {
    padding: 15px 0;
    font-size: 12px;
    text-align: center;
    background-color: #fff;

    .van-icon {
      display: block;
      font-size: 24px;
    }
  }
}
</style>
